### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by Daniel-olaO**

### CODE REVIEW

**Review by Russell-Pollari — DISMISSED** [review]

**Comment by Russell-Pollari** [comment]
Looks like you're `master` branch has a `lint` script in `package.json` but not this branch. I recommend adding it here to make sure your GH action runs correctly

**Comment by Daniel-olaO** [comment]
I don't think these branch should have a package.json, this just for the GH Actions

**Comment by Russell-Pollari** [comment]
your GH action is trying to run `npm run lint`. This assumes `lint` is a defined script in your package.json. 

I think this is already in your `master` branch, so try merging your master branch into this one. Or just add it to `package.json` in this branch

**Comment by Daniel-olaO** [comment]
Ready to merge

**Review by Russell-Pollari — APPROVED** [review]

**Pull request merged**
